version: "3"
services:
  nginx:
    container_name: nginx
    depends_on:
      - nest
      - next
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - app-network
  nest:
    build:
      dockerfile: Dockerfile.dev
      context: ./nest
    volumes:
      - /app/node_modules
      - ./nest:/app
    networks:
      - app-network
  next:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./next
    volumes:
      - /app/node_modules
      - ./next:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
