FROM node:14.14.0-alpine as builder
WORKDIR '/app'
COPY ./package.json ./
RUN yarn install
COPY . .
RUN yarn build
CMD ["yarn", "dev"]

FROM nginx
EXPOSE 3000
COPY ./nginx/default.cong/ /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html